### ISSUE TITLE
Selected images for menu dropdown

### ISSUE THREAD

**Issue by sagittaeri** [WatercressStudios/This-Was-For-You.#4]
https://cdn.discordapp.com/attachments/417852345729417216/553866224065314826/unknown.png

Asset somewhere in drive: https://drive.google.com/drive/u/0/folders/1ZzOs7fTFVKsoDTZQSBDvoYPtv7KllGIx

**Comment by Happiness-plus** [comment]
@sagittaeri 
Okay, so what exactly is the task here?

**Comment by sagittaeri** [comment]
See the end of this document: https://docs.google.com/document/d/1cKkxwaJZsgQXxao2ksRI1l1U8TGMydF6mWK0vN-hINc/edit#heading=h.ql0erqjy7zwe

Basically, to implement the on hover image change behaviours.
